env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "yuzu-api-01-dae6611de7aa.json"

runtime: python311

instance_class: F4

# Specify the maximum number of instances
automatic_scaling:
  max_instances: 7